# Generated by Django 5.0.1 on 2024-01-29 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_name', models.CharField(max_length=100)),
                ('ocr_text', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=50)),
                ('pnoms', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('corps', models.CharField(max_length=50)),
                ('first_date', models.CharField(max_length=20)),
                ('last_date', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=50)),
                ('document_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.documentdata')),
            ],
        ),
    ]
