# Generated by Django 5.0.1 on 2024-02-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdata',
            name='ocr_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
